# Generated by Django 4.2.11 on 2025-08-21 16:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0002_alter_availability_options_and_more'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=15, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='medium', max_length=15, verbose_name='Priority')),
                ('urgency_level', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('emergency', 'Emergency'), ('stat', 'STAT')], default='routine', max_length=15, verbose_name='Urgency Level')),
                ('specialty_text', models.CharField(default='General', max_length=100, verbose_name='Specialty (Text)')),
                ('chief_complaint', models.TextField(verbose_name='Chief Complaint')),
                ('clinical_summary', models.TextField(verbose_name='Clinical Summary')),
                ('reason', models.TextField(verbose_name='Reason for Referral')),
                ('relevant_history', models.TextField(blank=True, verbose_name='Relevant Medical History')),
                ('current_medications', models.TextField(blank=True, verbose_name='Current Medications')),
                ('allergies', models.TextField(blank=True, verbose_name='Known Allergies')),
                ('notes', models.TextField(blank=True, verbose_name='Additional Notes')),
                ('response_notes', models.TextField(blank=True, verbose_name='Response Notes')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Internal Notes')),
                ('attachments', models.FileField(blank=True, upload_to='referrals/attachments/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])], verbose_name='Attachments')),
                ('ambulance_required', models.BooleanField(default=False, verbose_name='Ambulance Required')),
                ('transport_urgency', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('emergency', 'Emergency'), ('stat', 'STAT')], default='routine', max_length=15, verbose_name='Transport Urgency')),
                ('special_requirements', models.TextField(blank=True, verbose_name='Special Requirements')),
                ('requested_appointment_date', models.DateTimeField(blank=True, null=True, verbose_name='Requested Appointment Date')),
                ('viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Viewed At')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Responded At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelled At')),
                ('estimated_wait_time', models.DurationField(blank=True, null=True, verbose_name='Estimated Wait Time')),
                ('follow_up_required', models.BooleanField(default=False, verbose_name='Follow-up Required')),
                ('follow_up_instructions', models.TextField(blank=True, verbose_name='Follow-up Instructions')),
                ('satisfaction_rating', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Satisfaction Rating')),
                ('feedback', models.TextField(blank=True, verbose_name='Feedback')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='patients.patient', verbose_name='Patient')),
                ('referring_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_referrals', to='doctors.doctorprofile', verbose_name='Referring Doctor')),
                ('referring_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_referrals', to='doctors.hospital', verbose_name='Referring Hospital')),
                ('response_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_responses', to=settings.AUTH_USER_MODEL, verbose_name='Responded By')),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.specialty', verbose_name='Specialty')),
                ('target_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_referrals', to='doctors.doctorprofile', verbose_name='Target Doctor')),
                ('target_hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_referrals', to='doctors.hospital', verbose_name='Target Hospital')),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referrals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=100)),
                ('template_text', models.TextField()),
                ('required_fields', models.JSONField(default=list)),
                ('is_public', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.specialty')),
            ],
            options={
                'verbose_name': 'Referral Template',
                'verbose_name_plural': 'Referral Templates',
            },
        ),
        migrations.CreateModel(
            name='ReferralStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('old_status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=15)),
                ('new_status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=15)),
                ('reason', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='referrals.referral')),
            ],
            options={
                'verbose_name': 'Referral Status History',
                'verbose_name_plural': 'Referral Status Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('file', models.FileField(upload_to='referrals/attachments/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'dicom'])])),
                ('file_type', models.CharField(choices=[('medical_record', 'Medical Record'), ('lab_result', 'Lab Result'), ('imaging', 'Medical Imaging'), ('prescription', 'Prescription'), ('other', 'Other')], max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_attachments', to='referrals.referral')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral Attachment',
                'verbose_name_plural': 'Referral Attachments',
            },
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['status', 'priority'], name='referrals_r_status_6da231_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referring_doctor', 'status'], name='referrals_r_referri_3a8e44_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['target_doctor', 'status'], name='referrals_r_target__01e601_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['patient', 'status'], name='referrals_r_patient_fc132b_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['created_at', 'status'], name='referrals_r_created_bec13f_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['urgency_level', 'created_at'], name='referrals_r_urgency_1d085d_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['ambulance_required', 'status'], name='referrals_r_ambulan_361ae0_idx'),
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.CheckConstraint(check=models.Q(('satisfaction_rating__gte', 1), ('satisfaction_rating__lte', 5)), name='valid_satisfaction_rating'),
        ),
    ]
