# Generated by Django 4.2.11 on 2025-08-21 20:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ambulances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('call_number', models.CharField(max_length=20, unique=True, verbose_name='Call Number')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Call Received At')),
                ('caller_phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid phone number', regex='^\\+?1?\\d{9,15}$')], verbose_name='Caller Phone')),
                ('caller_name', models.CharField(blank=True, max_length=100, verbose_name='Caller Name')),
                ('caller_relationship', models.CharField(blank=True, max_length=50, verbose_name='Relationship to Patient')),
                ('call_type', models.CharField(choices=[('medical', 'Medical Emergency'), ('trauma', 'Trauma/Accident'), ('cardiac', 'Cardiac Emergency'), ('respiratory', 'Respiratory Emergency'), ('psychiatric', 'Psychiatric Emergency'), ('obstetric', 'Obstetric Emergency'), ('pediatric', 'Pediatric Emergency'), ('overdose', 'Drug Overdose'), ('burn', 'Burn Injury'), ('poisoning', 'Poisoning'), ('other', 'Other Emergency')], max_length=20, verbose_name='Call Type')),
                ('priority', models.CharField(choices=[('critical', 'Critical - Life Threatening'), ('emergency', 'Emergency - Urgent'), ('urgent', 'Urgent - Non-Life Threatening'), ('routine', 'Routine Transport')], max_length=20, verbose_name='Priority Level')),
                ('status', models.CharField(choices=[('received', 'Call Received'), ('processing', 'Processing'), ('dispatched', 'Ambulance Dispatched'), ('completed', 'Call Completed'), ('cancelled', 'Call Cancelled'), ('transferred', 'Transferred to Other Agency')], default='received', max_length=20, verbose_name='Call Status')),
                ('incident_address', models.TextField(verbose_name='Incident Address')),
                ('landmark_description', models.TextField(blank=True, verbose_name='Landmark Description')),
                ('access_instructions', models.TextField(blank=True, verbose_name='Access Instructions')),
                ('patient_name', models.CharField(blank=True, max_length=100, verbose_name='Patient Name')),
                ('patient_age', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)], verbose_name='Patient Age')),
                ('patient_gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')], max_length=10, verbose_name='Patient Gender')),
                ('patient_consciousness', models.CharField(blank=True, choices=[('conscious', 'Conscious and Alert'), ('drowsy', 'Drowsy/Confused'), ('unconscious', 'Unconscious'), ('unknown', 'Unknown')], max_length=20, verbose_name='Consciousness Level')),
                ('patient_breathing', models.CharField(blank=True, choices=[('normal', 'Normal Breathing'), ('difficulty', 'Difficulty Breathing'), ('not_breathing', 'Not Breathing'), ('unknown', 'Unknown')], max_length=20, verbose_name='Breathing Status')),
                ('chief_complaint', models.TextField(verbose_name='Chief Complaint')),
                ('symptoms_description', models.TextField(blank=True, verbose_name='Symptoms Description')),
                ('medical_history', models.TextField(blank=True, verbose_name='Relevant Medical History')),
                ('medications', models.TextField(blank=True, verbose_name='Current Medications')),
                ('allergies', models.TextField(blank=True, verbose_name='Known Allergies')),
                ('call_duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Call Duration (seconds)')),
                ('dispatch_time', models.DateTimeField(blank=True, null=True, verbose_name='Dispatch Time')),
                ('response_time_target', models.PositiveIntegerField(default=8, verbose_name='Response Time Target (minutes)')),
                ('special_instructions', models.TextField(blank=True, verbose_name='Special Instructions')),
                ('hazards_present', models.BooleanField(default=False, verbose_name='Hazards Present')),
                ('hazard_description', models.TextField(blank=True, verbose_name='Hazard Description')),
                ('police_required', models.BooleanField(default=False, verbose_name='Police Required')),
                ('fire_required', models.BooleanField(default=False, verbose_name='Fire Department Required')),
                ('call_recording_url', models.URLField(blank=True, verbose_name='Call Recording URL')),
                ('call_notes', models.TextField(blank=True, verbose_name='Call Notes')),
                ('call_taker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_calls_taken', to=settings.AUTH_USER_MODEL, verbose_name='Call Taker')),
                ('dispatcher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_calls_dispatched', to=settings.AUTH_USER_MODEL, verbose_name='Dispatcher')),
            ],
            options={
                'verbose_name': 'Emergency Call',
                'verbose_name_plural': 'Emergency Calls',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='CallStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('old_status', models.CharField(max_length=20, verbose_name='Previous Status')),
                ('new_status', models.CharField(max_length=20, verbose_name='New Status')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Changed At')),
                ('notes', models.TextField(blank=True, verbose_name='Change Notes')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Changed By')),
                ('emergency_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='ambulances.emergencycall')),
            ],
            options={
                'verbose_name': 'Call Status History',
                'verbose_name_plural': 'Call Status Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CallPriorityAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('chest_pain', models.BooleanField(default=False, verbose_name='Chest Pain')),
                ('difficulty_breathing', models.BooleanField(default=False, verbose_name='Difficulty Breathing')),
                ('unconscious', models.BooleanField(default=False, verbose_name='Unconscious')),
                ('severe_bleeding', models.BooleanField(default=False, verbose_name='Severe Bleeding')),
                ('cardiac_arrest', models.BooleanField(default=False, verbose_name='Cardiac Arrest')),
                ('stroke_symptoms', models.BooleanField(default=False, verbose_name='Stroke Symptoms')),
                ('severe_trauma', models.BooleanField(default=False, verbose_name='Severe Trauma')),
                ('overdose', models.BooleanField(default=False, verbose_name='Drug Overdose')),
                ('allergic_reaction', models.BooleanField(default=False, verbose_name='Severe Allergic Reaction')),
                ('pregnancy_complications', models.BooleanField(default=False, verbose_name='Pregnancy Complications')),
                ('calculated_priority', models.CharField(max_length=20, verbose_name='Calculated Priority')),
                ('priority_score', models.PositiveIntegerField(default=0, verbose_name='Priority Score')),
                ('assessment_notes', models.TextField(blank=True, verbose_name='Assessment Notes')),
                ('assessed_at', models.DateTimeField(auto_now_add=True, verbose_name='Assessed At')),
                ('assessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Assessed By')),
                ('emergency_call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='priority_assessment', to='ambulances.emergencycall')),
            ],
            options={
                'verbose_name': 'Call Priority Assessment',
                'verbose_name_plural': 'Call Priority Assessments',
            },
        ),
        migrations.AddIndex(
            model_name='emergencycall',
            index=models.Index(fields=['call_number'], name='ambulances__call_nu_369823_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencycall',
            index=models.Index(fields=['status', 'priority'], name='ambulances__status_e43a5d_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencycall',
            index=models.Index(fields=['received_at'], name='ambulances__receive_db98df_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencycall',
            index=models.Index(fields=['caller_phone'], name='ambulances__caller__8029c7_idx'),
        ),
    ]
