# Generated by Django 4.2.11 on 2025-08-20 20:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0003_alter_report_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentanalytics',
            name='avg_appointment_duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Average Appointment Duration'),
        ),
        migrations.AlterField(
            model_name='appointmentanalytics',
            name='avg_wait_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Average Wait Time'),
        ),
        migrations.AlterField(
            model_name='appointmentanalytics',
            name='cancelled_appointments',
            field=models.IntegerField(default=0, verbose_name='Cancelled Appointments'),
        ),
        migrations.AlterField(
            model_name='appointmentanalytics',
            name='completed_appointments',
            field=models.IntegerField(default=0, verbose_name='Completed Appointments'),
        ),
        migrations.AlterField(
            model_name='appointmentanalytics',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='appointmentanalytics',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='appointmentanalytics',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='appointmentanalytics',
            name='no_show_appointments',
            field=models.IntegerField(default=0, verbose_name='No Show Appointments'),
        ),
        migrations.AlterField(
            model_name='appointmentanalytics',
            name='no_show_rate',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='No Show Rate'),
        ),
        migrations.AlterField(
            model_name='appointmentanalytics',
            name='period_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20, verbose_name='Period Type'),
        ),
        migrations.AlterField(
            model_name='appointmentanalytics',
            name='scheduled_appointments',
            field=models.IntegerField(default=0, verbose_name='Scheduled Appointments'),
        ),
        migrations.AlterField(
            model_name='appointmentanalytics',
            name='total_appointments',
            field=models.IntegerField(default=0, verbose_name='Total Appointments'),
        ),
        migrations.AlterField(
            model_name='appointmentanalytics',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='appointmentanalytics',
            name='utilization_rate',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Utilization Rate'),
        ),
        migrations.AlterField(
            model_name='compliancereport',
            name='compliance_score',
            field=models.FloatField(default=100.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Compliance Score'),
        ),
        migrations.AlterField(
            model_name='compliancereport',
            name='compliant_events',
            field=models.IntegerField(default=0, verbose_name='Compliant Events'),
        ),
        migrations.AlterField(
            model_name='compliancereport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='compliancereport',
            name='findings',
            field=models.JSONField(default=list, verbose_name='Findings'),
        ),
        migrations.AlterField(
            model_name='compliancereport',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Generated By'),
        ),
        migrations.AlterField(
            model_name='compliancereport',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='compliancereport',
            name='non_compliant_events',
            field=models.IntegerField(default=0, verbose_name='Non-Compliant Events'),
        ),
        migrations.AlterField(
            model_name='compliancereport',
            name='period_end',
            field=models.DateTimeField(verbose_name='Period End'),
        ),
        migrations.AlterField(
            model_name='compliancereport',
            name='period_start',
            field=models.DateTimeField(verbose_name='Period Start'),
        ),
        migrations.AlterField(
            model_name='compliancereport',
            name='recommendations',
            field=models.JSONField(default=list, verbose_name='Recommendations'),
        ),
        migrations.AlterField(
            model_name='compliancereport',
            name='report_type',
            field=models.CharField(choices=[('hipaa', 'HIPAA Compliance'), ('gdpr', 'GDPR Compliance'), ('audit_trail', 'Audit Trail'), ('data_access', 'Data Access Log'), ('security', 'Security Report'), ('quality', 'Quality Assurance')], max_length=50, verbose_name='Report Type'),
        ),
        migrations.AlterField(
            model_name='compliancereport',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At'),
        ),
        migrations.AlterField(
            model_name='compliancereport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_compliance_reports', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By'),
        ),
        migrations.AlterField(
            model_name='compliancereport',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20, verbose_name='Risk Level'),
        ),
        migrations.AlterField(
            model_name='compliancereport',
            name='total_events',
            field=models.IntegerField(default=0, verbose_name='Total Events'),
        ),
        migrations.AlterField(
            model_name='compliancereport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='referralanalytics',
            name='acceptance_rate',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Acceptance Rate'),
        ),
        migrations.AlterField(
            model_name='referralanalytics',
            name='accepted_referrals',
            field=models.IntegerField(default=0, verbose_name='Accepted Referrals'),
        ),
        migrations.AlterField(
            model_name='referralanalytics',
            name='avg_completion_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Average Completion Time'),
        ),
        migrations.AlterField(
            model_name='referralanalytics',
            name='avg_response_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Average Response Time'),
        ),
        migrations.AlterField(
            model_name='referralanalytics',
            name='completed_referrals',
            field=models.IntegerField(default=0, verbose_name='Completed Referrals'),
        ),
        migrations.AlterField(
            model_name='referralanalytics',
            name='completion_rate',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Completion Rate'),
        ),
        migrations.AlterField(
            model_name='referralanalytics',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='referralanalytics',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='referralanalytics',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='referralanalytics',
            name='pending_referrals',
            field=models.IntegerField(default=0, verbose_name='Pending Referrals'),
        ),
        migrations.AlterField(
            model_name='referralanalytics',
            name='period_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20, verbose_name='Period Type'),
        ),
        migrations.AlterField(
            model_name='referralanalytics',
            name='rejected_referrals',
            field=models.IntegerField(default=0, verbose_name='Rejected Referrals'),
        ),
        migrations.AlterField(
            model_name='referralanalytics',
            name='specialty_breakdown',
            field=models.JSONField(default=dict, verbose_name='Specialty Breakdown'),
        ),
        migrations.AlterField(
            model_name='referralanalytics',
            name='total_referrals',
            field=models.IntegerField(default=0, verbose_name='Total Referrals'),
        ),
        migrations.AlterField(
            model_name='referralanalytics',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='report',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completed At'),
        ),
        migrations.AlterField(
            model_name='report',
            name='content',
            field=models.TextField(blank=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_from',
            field=models.DateField(blank=True, null=True, verbose_name='Date From'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_to',
            field=models.DateField(blank=True, null=True, verbose_name='Date To'),
        ),
        migrations.AlterField(
            model_name='report',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='Error Message'),
        ),
        migrations.AlterField(
            model_name='report',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='File Path'),
        ),
        migrations.AlterField(
            model_name='report',
            name='format',
            field=models.CharField(choices=[('html', 'HTML'), ('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON')], default='html', max_length=10, verbose_name='Format'),
        ),
        migrations.AlterField(
            model_name='report',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL, verbose_name='Generated By'),
        ),
        migrations.AlterField(
            model_name='report',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='report',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Is Public'),
        ),
        migrations.AlterField(
            model_name='report',
            name='parameters',
            field=models.JSONField(default=dict, verbose_name='Parameters'),
        ),
        migrations.AlterField(
            model_name='report',
            name='processing_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Processing Time'),
        ),
        migrations.AlterField(
            model_name='report',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_reports', to=settings.AUTH_USER_MODEL, verbose_name='Shared With'),
        ),
        migrations.AlterField(
            model_name='report',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Started At'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='report',
            name='summary',
            field=models.JSONField(default=dict, help_text='Report summary statistics', verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='report',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.reporttemplate', verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='reportaccess',
            name='accessed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Accessed At'),
        ),
        migrations.AlterField(
            model_name='reportaccess',
            name='action',
            field=models.CharField(choices=[('view', 'Viewed'), ('download', 'Downloaded'), ('share', 'Shared'), ('export', 'Exported')], max_length=50, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='reportaccess',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='reportaccess',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='reportaccess',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='reportaccess',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='reports.report', verbose_name='Report'),
        ),
        migrations.AlterField(
            model_name='reportaccess',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='reportaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='reportaccess',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='day_of_month',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Day of Month'),
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='day_of_week',
            field=models.IntegerField(blank=True, help_text='0=Monday, 6=Sunday', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='Day of Week'),
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='default_parameters',
            field=models.JSONField(default=dict, verbose_name='Default Parameters'),
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('on_demand', 'On Demand')], max_length=20, verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='Is Enabled'),
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='last_run',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Run'),
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='next_run',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Next Run'),
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='recipients',
            field=models.ManyToManyField(help_text='Users who will receive the scheduled report', to=settings.AUTH_USER_MODEL, verbose_name='Recipients'),
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.reporttemplate', verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='time_of_day',
            field=models.TimeField(default='09:00', verbose_name='Time of Day'),
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='auto_generate',
            field=models.BooleanField(default=False, verbose_name='Auto Generate'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('on_demand', 'On Demand')], default='on_demand', max_length=20, verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='parameters',
            field=models.JSONField(default=dict, help_text='Report parameters and filters', verbose_name='Parameters'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='query_template',
            field=models.TextField(help_text='SQL query template for the report', verbose_name='Query Template'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='recipients',
            field=models.ManyToManyField(blank=True, help_text='Users who receive this report automatically', to=settings.AUTH_USER_MODEL, verbose_name='Recipients'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='report_type',
            field=models.CharField(choices=[('referral_analytics', 'Referral Analytics'), ('appointment_analytics', 'Appointment Analytics'), ('patient_demographics', 'Patient Demographics'), ('doctor_performance', 'Doctor Performance'), ('system_usage', 'System Usage'), ('compliance', 'Compliance Report'), ('financial', 'Financial Report'), ('quality_metrics', 'Quality Metrics'), ('wait_times', 'Wait Times Analysis'), ('custom', 'Custom Report')], max_length=50, verbose_name='Report Type'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='systemusageanalytics',
            name='active_users',
            field=models.IntegerField(default=0, verbose_name='Active Users'),
        ),
        migrations.AlterField(
            model_name='systemusageanalytics',
            name='avg_response_time',
            field=models.FloatField(default=0.0, verbose_name='Average Response Time'),
        ),
        migrations.AlterField(
            model_name='systemusageanalytics',
            name='avg_session_duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Average Session Duration'),
        ),
        migrations.AlterField(
            model_name='systemusageanalytics',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='systemusageanalytics',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='systemusageanalytics',
            name='error_rate',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Error Rate'),
        ),
        migrations.AlterField(
            model_name='systemusageanalytics',
            name='feature_usage',
            field=models.JSONField(default=dict, verbose_name='Feature Usage'),
        ),
        migrations.AlterField(
            model_name='systemusageanalytics',
            name='hour',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='Hour'),
        ),
        migrations.AlterField(
            model_name='systemusageanalytics',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='systemusageanalytics',
            name='new_users',
            field=models.IntegerField(default=0, verbose_name='New Users'),
        ),
        migrations.AlterField(
            model_name='systemusageanalytics',
            name='page_views',
            field=models.IntegerField(default=0, verbose_name='Page Views'),
        ),
        migrations.AlterField(
            model_name='systemusageanalytics',
            name='total_sessions',
            field=models.IntegerField(default=0, verbose_name='Total Sessions'),
        ),
        migrations.AlterField(
            model_name='systemusageanalytics',
            name='total_users',
            field=models.IntegerField(default=0, verbose_name='Total Users'),
        ),
        migrations.AlterField(
            model_name='systemusageanalytics',
            name='unique_page_views',
            field=models.IntegerField(default=0, verbose_name='Unique Page Views'),
        ),
        migrations.AlterField(
            model_name='systemusageanalytics',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.CreateModel(
            name='ReportShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('share_type', models.CharField(choices=[('internal', 'Internal User'), ('external', 'External Email'), ('public_link', 'Public Link'), ('department', 'Department'), ('role', 'Role-based')], max_length=20, verbose_name='Share Type')),
                ('permission_level', models.CharField(choices=[('view', 'View Only'), ('download', 'View and Download'), ('comment', 'View, Download and Comment'), ('edit', 'Full Access')], default='view', max_length=20, verbose_name='Permission Level')),
                ('external_email', models.EmailField(blank=True, max_length=254, verbose_name='External Email')),
                ('external_name', models.CharField(blank=True, max_length=100, verbose_name='External Name')),
                ('share_token', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Share Token')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('access_count', models.IntegerField(default=0, verbose_name='Access Count')),
                ('max_access_count', models.IntegerField(blank=True, null=True, verbose_name='Max Access Count')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('notify_on_access', models.BooleanField(default=False, verbose_name='Notify on Access')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='reports.report', verbose_name='Report')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_reports_by', to=settings.AUTH_USER_MODEL, verbose_name='Shared By')),
                ('shared_with_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_report_shares', to=settings.AUTH_USER_MODEL, verbose_name='Shared With User')),
            ],
            options={
                'verbose_name': 'Report Share',
                'verbose_name_plural': 'Report Shares',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('filter_type', models.CharField(choices=[('date_range', 'Date Range'), ('user_filter', 'User Filter'), ('department', 'Department'), ('specialty', 'Specialty'), ('status', 'Status'), ('priority', 'Priority'), ('custom', 'Custom Filter')], max_length=20, verbose_name='Filter Type')),
                ('filter_config', models.JSONField(default=dict, help_text='Filter configuration and parameters', verbose_name='Filter Configuration')),
                ('is_public', models.BooleanField(default=False, verbose_name='Is Public')),
                ('usage_count', models.IntegerField(default=0, verbose_name='Usage Count')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_filters', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_filters', to=settings.AUTH_USER_MODEL, verbose_name='Shared With')),
            ],
            options={
                'verbose_name': 'Report Filter',
                'verbose_name_plural': 'Report Filters',
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('export_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON'), ('xml', 'XML'), ('word', 'Word Document')], max_length=10, verbose_name='Export Format')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20, verbose_name='Status')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='exports/', verbose_name='File Path')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='File Size')),
                ('download_count', models.IntegerField(default=0, verbose_name='Download Count')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('export_parameters', models.JSONField(default=dict, verbose_name='Export Parameters')),
                ('processing_time', models.DurationField(blank=True, null=True, verbose_name='Processing Time')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('exported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Exported By')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='reports.report', verbose_name='Report')),
            ],
            options={
                'verbose_name': 'Report Export',
                'verbose_name_plural': 'Report Exports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('comment_type', models.CharField(choices=[('general', 'General Comment'), ('question', 'Question'), ('suggestion', 'Suggestion'), ('issue', 'Issue'), ('approval', 'Approval'), ('rejection', 'Rejection')], default='general', max_length=20, verbose_name='Comment Type')),
                ('content', models.TextField(verbose_name='Content')),
                ('page_number', models.IntegerField(blank=True, null=True, verbose_name='Page Number')),
                ('position_x', models.FloatField(blank=True, null=True, verbose_name='Position X')),
                ('position_y', models.FloatField(blank=True, null=True, verbose_name='Position Y')),
                ('highlighted_text', models.TextField(blank=True, verbose_name='Highlighted Text')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Is Resolved')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('is_private', models.BooleanField(default=False, verbose_name='Is Private')),
                ('attachments', models.JSONField(default=list, verbose_name='Attachments')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='reports.reportcomment', verbose_name='Parent Comment')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reports.report', verbose_name='Report')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_comments', to=settings.AUTH_USER_MODEL, verbose_name='Resolved By')),
            ],
            options={
                'verbose_name': 'Report Comment',
                'verbose_name_plural': 'Report Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('color', models.CharField(default='#007bff', help_text='Hex color code', max_length=7, verbose_name='Color')),
                ('icon', models.CharField(blank=True, help_text='CSS icon class', max_length=50, verbose_name='Icon')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sort Order')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='reports.reportcategory', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Report Category',
                'verbose_name_plural': 'Report Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.reportcategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.reportcategory', verbose_name='Category'),
        ),
    ]
