# Generated by Django 4.2.11 on 2025-08-21 10:31

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ['date', 'start_time'], 'verbose_name': 'Availability', 'verbose_name_plural': 'Availability Slots'},
        ),
        migrations.AlterModelOptions(
            name='doctorprofile',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Doctor Profile', 'verbose_name_plural': 'Doctor Profiles'},
        ),
        migrations.AlterModelOptions(
            name='doctorreview',
            options={'ordering': ['-created_at'], 'verbose_name': 'Doctor Review', 'verbose_name_plural': 'Doctor Reviews'},
        ),
        migrations.AlterModelOptions(
            name='emergencycontact',
            options={'ordering': ['-is_primary', 'name'], 'verbose_name': 'Emergency Contact', 'verbose_name_plural': 'Emergency Contacts'},
        ),
        migrations.AlterModelOptions(
            name='hospital',
            options={'ordering': ['name'], 'verbose_name': 'Hospital', 'verbose_name_plural': 'Hospitals'},
        ),
        migrations.AlterModelOptions(
            name='referralstats',
            options={'ordering': ['-last_updated'], 'verbose_name': 'Referral Statistics', 'verbose_name_plural': 'Referral Statistics'},
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'ordering': ['name'], 'verbose_name': 'Specialty', 'verbose_name_plural': 'Specialties'},
        ),
        migrations.AddField(
            model_name='availability',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='doctorreview',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='referralstats',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referralstats',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='referralstats',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='appointment_type',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('follow_up', 'Follow-up'), ('emergency', 'Emergency'), ('procedure', 'Procedure'), ('telehealth', 'Telehealth')], default='consultation', max_length=50, verbose_name='Appointment Type'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='current_bookings',
            field=models.PositiveIntegerField(default=0, verbose_name='Current Bookings'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='doctors.doctorprofile', verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='end_time',
            field=models.TimeField(verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Google Calendar Event ID'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='Is Recurring'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_availability', to='doctors.hospital', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='max_patients',
            field=models.PositiveIntegerField(default=1, verbose_name='Max Patients'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='recurring_until',
            field=models.DateField(blank=True, null=True, verbose_name='Recurring Until'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='slot_duration',
            field=models.PositiveIntegerField(default=30, help_text='Duration in minutes', verbose_name='Slot Duration'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='start_time',
            field=models.TimeField(verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('blocked', 'Blocked'), ('emergency', 'Emergency Only')], default='available', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='weekday',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10, verbose_name='Weekday'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='accepts_insurance',
            field=models.BooleanField(default=True, verbose_name='Accepts Insurance'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='accepts_referrals',
            field=models.BooleanField(default=True, verbose_name='Accepts Referrals'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='affiliated_hospitals',
            field=models.ManyToManyField(blank=True, related_name='affiliated_doctors', to='doctors.hospital', verbose_name='Affiliated Hospitals'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Average Rating'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='board_certifications',
            field=models.TextField(blank=True, help_text='List certifications separated by commas', verbose_name='Board Certifications'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='city',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Consultation Fee'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='dea_number',
            field=models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator(message='DEA number format: XX1234567', regex='^[A-Z]{2}\\d{7}$')], verbose_name='DEA Number'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='emergency_availability',
            field=models.BooleanField(default=False, verbose_name='Emergency Availability'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Emergency Phone'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='fellowship_programs',
            field=models.TextField(blank=True, help_text='List fellowship programs separated by commas', verbose_name='Fellowship Programs'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer not to say')], max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='graduation_year',
            field=models.PositiveIntegerField(verbose_name='Graduation Year'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='languages_spoken',
            field=models.CharField(blank=True, help_text='Languages separated by commas', max_length=200, verbose_name='Languages Spoken'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='license_expiry_date',
            field=models.DateField(verbose_name='License Expiry Date'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='license_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='License Number'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='license_state',
            field=models.CharField(max_length=50, verbose_name='License State'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='max_patients_per_day',
            field=models.PositiveIntegerField(default=20, verbose_name='Max Patients Per Day'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='medical_school',
            field=models.CharField(max_length=200, verbose_name='Medical School'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='npi_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='NPI must be 10 digits', regex='^\\d{10}$')], verbose_name='NPI Number'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='office_address',
            field=models.TextField(verbose_name='Office Address'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='primary_hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_doctors', to='doctors.hospital', verbose_name='Primary Hospital'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='primary_specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_doctors', to='doctors.specialty', verbose_name='Primary Specialty'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/photos/', verbose_name='Profile Photo'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='referral_acceptance_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Referral Acceptance Rate'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='residency_program',
            field=models.CharField(max_length=200, verbose_name='Residency Program'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialties',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='doctors.specialty', verbose_name='Specialties'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='state',
            field=models.CharField(max_length=50, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='telehealth_available',
            field=models.BooleanField(default=False, verbose_name='Telehealth Available'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Reviews'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verification Date'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20, verbose_name='Verification Status'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_doctors', to=settings.AUTH_USER_MODEL, verbose_name='Verified By'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0, verbose_name='Years of Experience'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='zip_code',
            field=models.CharField(max_length=10, verbose_name='ZIP Code'),
        ),
        migrations.AlterField(
            model_name='doctorreview',
            name='bedside_manner_rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Bedside Manner Rating'),
        ),
        migrations.AlterField(
            model_name='doctorreview',
            name='communication_rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Communication Rating'),
        ),
        migrations.AlterField(
            model_name='doctorreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='doctorreview',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='doctors.doctorprofile', verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='doctorreview',
            name='expertise_rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Expertise Rating'),
        ),
        migrations.AlterField(
            model_name='doctorreview',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Is Approved'),
        ),
        migrations.AlterField(
            model_name='doctorreview',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Is Verified'),
        ),
        migrations.AlterField(
            model_name='doctorreview',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Overall Rating'),
        ),
        migrations.AlterField(
            model_name='doctorreview',
            name='review_text',
            field=models.TextField(verbose_name='Review Text'),
        ),
        migrations.AlterField(
            model_name='doctorreview',
            name='review_title',
            field=models.CharField(max_length=200, verbose_name='Review Title'),
        ),
        migrations.AlterField(
            model_name='doctorreview',
            name='reviewer_email',
            field=models.EmailField(max_length=254, verbose_name='Reviewer Email'),
        ),
        migrations.AlterField(
            model_name='doctorreview',
            name='reviewer_name',
            field=models.CharField(max_length=100, verbose_name='Reviewer Name'),
        ),
        migrations.AlterField(
            model_name='doctorreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='doctorreview',
            name='visit_date',
            field=models.DateField(verbose_name='Visit Date'),
        ),
        migrations.AlterField(
            model_name='doctorreview',
            name='would_recommend',
            field=models.BooleanField(default=True, verbose_name='Would Recommend'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='doctors.doctorprofile', verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Is Primary Contact'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='relationship',
            field=models.CharField(max_length=50, verbose_name='Relationship'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='accreditation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Accreditation'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='bed_capacity',
            field=models.PositiveIntegerField(default=0, verbose_name='Bed Capacity'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='city',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='emergency_services',
            field=models.BooleanField(default=True, verbose_name='Emergency Services'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Hospital Name'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='state',
            field=models.CharField(max_length=50, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='trauma_center_level',
            field=models.CharField(choices=[('I', 'Level I'), ('II', 'Level II'), ('III', 'Level III'), ('IV', 'Level IV'), ('N/A', 'Not Applicable')], default='N/A', max_length=10, verbose_name='Trauma Center Level'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='type',
            field=models.CharField(choices=[('general', 'General Hospital'), ('specialty', 'Specialty Hospital'), ('clinic', 'Clinic'), ('emergency', 'Emergency Center'), ('rehabilitation', 'Rehabilitation Center'), ('psychiatric', 'Psychiatric Hospital')], max_length=50, verbose_name='Hospital Type'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='zip_code',
            field=models.CharField(max_length=10, verbose_name='ZIP Code'),
        ),
        migrations.AlterField(
            model_name='referralstats',
            name='average_response_time',
            field=models.DurationField(default=datetime.timedelta(days=1), verbose_name='Average Response Time'),
        ),
        migrations.AlterField(
            model_name='referralstats',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_stats', to='doctors.doctorprofile', verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='referralstats',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='referralstats',
            name='referrals_accepted',
            field=models.PositiveIntegerField(default=0, verbose_name='Referrals Accepted'),
        ),
        migrations.AlterField(
            model_name='referralstats',
            name='referrals_declined',
            field=models.PositiveIntegerField(default=0, verbose_name='Referrals Declined'),
        ),
        migrations.AlterField(
            model_name='referralstats',
            name='referrals_pending',
            field=models.PositiveIntegerField(default=0, verbose_name='Referrals Pending'),
        ),
        migrations.AlterField(
            model_name='referralstats',
            name='total_referrals_received',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Referrals Received'),
        ),
        migrations.AlterField(
            model_name='referralstats',
            name='total_referrals_sent',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Referrals Sent'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Specialty Code'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Specialty Name'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='parent_specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subspecialties', to='doctors.specialty', verbose_name='Parent Specialty'),
        ),
    ]
